### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by vaijab** [UKHomeOffice/kb8or#1]

**Comment by vaijab** [comment]
:-(

**Comment by lewismarshall** [comment]
?

On Thursday, September 3, 2015, Vaidas Jablonskis notifications@github.com
wrote:

> :-(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UKHomeOffice/kb8or/issues/1#issuecomment-137422568.

## 

Lewis

Mobile: 0788 757 3297

My web sites:

blog.deploymentsource.com
http://blog.deploymentsource.com/
uk.linkedin.com/in/lewismarshall
http://uk.linkedin.com/in/lewismarshallwww.itkeys.co.uk

**Comment by vaijab** [comment]
@lewismarshall you just closed the issue without saying why :-)

**Comment by lewismarshall** [comment]
Sorry - added a license :)

On Thu, Sep 3, 2015 at 2:35 PM, Vaidas Jablonskis notifications@github.com
wrote:

> @lewismarshall https://github.com/lewismarshall you just closed the
> issue without saying why :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UKHomeOffice/kb8or/issues/1#issuecomment-137447367.

## 

Lewis

Mobile: 0788 757 3297

My web sites:

blog.deploymentsource.com
http://blog.deploymentsource.com/
uk.linkedin.com/in/lewismarshall
http://uk.linkedin.com/in/lewismarshallwww.itkeys.co.uk
