### ISSUE TITLE
Improve error handling when missing environment file

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/kb8or#4]
Current error handling isn't clear about what the issue is. If you specify an environment file that doesn't exist you get the following error:
E, [2015-09-06T20:35:47.688880 #1] ERROR -- : undefined method `has_key?' for nil:NilClass
E, [2015-09-06T20:35:47.688829 #1] ERROR -- : undefined method`has_key?' for nil:NilClass

To improve this it should check for the existence of the environment file and report a clearer error if it doesn't exist

**Comment by lewismarshall** [comment]
Fixed in v0.1.12

**Comment by lewismarshall** [comment]
Fixed in v0.1.12
