### ISSUE TITLE
consider using something else for variables instead of bash variables.

### ISSUE THREAD

**Issue by allandegnan** [UKHomeOffice/kb8or#54]
So, I might want to use ${ENV_SERVICE_HOST} as the value I pass through to a container.  Given that k8bor trys to evaluate this and causes problems if it does, leading me to trying to escape it.

We either figure out how to pass strings through like that in a reliable way or add something to kubernetes to ignore them or replace the variables with something else like maybe handlebars.

**Comment by lewismarshall** [comment]
Don't use the same variable names - But yes maybe a totally different variable delimiters could be good before we get too many resources that conflict.

Proposals:
1. `%{ my_var_name }`
2. `{{ my_var_name }}`
