### ISSUE TITLE
Use rolling update

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/kb8or#6]
Kubernetes gives us rolling update for free, which does rollback, no downtime, etc. We should use this

**Comment by lewismarshall** [comment]
I agree, totally. Pseudo code - ...ish:
1. Find the controller (using it's name in kb8or file). Discover is it's running (from the pods).
2. Find the selector for the pods
3. Run kubectl get pods with selector and get yaml out
4. Get version of old image
5. Initiate rolling update from old version to new...

**Comment by lewismarshall** [comment]
Now completed in https://github.com/UKHomeOffice/kb8or/pull/12
