### ISSUE TITLE
can't rolling upgrade a when in wait state.

### ISSUE THREAD

**Issue by allandegnan** [UKHomeOffice/kb8or#71]
If you have a pod in a crashLoopWait it won't let you do a rolling-upgrade and thus requires either manual intervention, or I assume luck in the timing if your request.  I'd like folks not to have direct kubectl access and thus would like to deal with this.

I think we can assume that a pod in crashLoopWait isn't working and can be deleted before we try again?

**Comment by lewismarshall** [comment]
Possibly. I guess rolling upgrades should be avoided if the pods are ALL unhealthy.

**Comment by allandegnan** [comment]
If they're all unhealthy I guess we could just delete then create.  I suppose that leaves an edge case of some being unhealthy, but that should be an unlikely edge case.
