### ISSUE TITLE
Kb8or fails with wrong files in secrets directory

### ISSUE THREAD

**Issue by ipedrazas** [UKHomeOffice/kb8or#84]
If kb8or finds a file that is not a secret in an ssl directory it fails non-gracefully :smile_cat: 

```
Error (exit code:'1') running 'kubectl create -f -':
The Secret "ssl-secrets" is invalid.
data[README.md]: invalid value 'README.md', Details: must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*

```

**Comment by lewismarshall** [comment]
This fails exactly as designed - `kubectl create -f -` fails as the secret is invalid. Kb8or doesn't check the kubernetes schema.

The error is actually the output from the command `kubectl create -f -`.

Kb8or also will give you the yaml that was given as input...

Let me know the expected behaviour though...

**Comment by ipedrazas** [comment]
Agreed, but... (there's always a but :smiley: ) with secrets is different, right? kb8or reads the cert and adds it as a secret.

The thing is that if someone puts a file in secrets/ssl/some_env that it's not a secret, kb8or fails with that error.

It would be good if kb8or had an option to decide what to do `onerror` for example, `onerror=ignore` or `onerror=abort` you see where I'm going. Or having the possibility of white listing errors 

```
ignore_errors: 
   - secrets
   - services 
```

or a way of dealing with a situation that "it's a controlled error"

**Comment by ipedrazas** [comment]
Another option would be to add a `.kb8orignore` file where we can put things like `*.md` to ignore all the markdown files...

**Comment by lewismarshall** [comment]
Sorry @ipedrazas, just not sold on new complexity to cope with errors... I don't think a secrets directory needs to cope with other file types, unless I'm missing something?
Definitely don't want to introduce any error to ignore.

Kb8or can read specific files or a whole directory (to create a secret dynamically) - see https://github.com/UKHomeOffice/kb8or/blob/master/docs/schema.md#filesecrets 

On reflection, I could change the schema, I was thinking this could be an array of "secrets" (to create more than one secret per deploy) e.g. it could also add a wildcard option to the path and glob the results e.g.:

```
FileSecrets:
- name: frontend-secrets
  path: ../secrets/${env}/myapp_frontend_secrets/*.sec
- name: tls
  path: ../secrets/${env}/certs/*.pem
```

You can also specify a secret as yaml directly and use variables read in from files e.g. https://github.com/UKHomeOffice/kb8or/blob/master/docs/schema.md#fnfiledata could be put before a `Deploys:` section.

**Comment by ipedrazas** [comment]
wow!

**Comment by lewismarshall** [comment]
:)

**Comment by ipedrazas** [comment]
It's ok. You're right. My deploy failed because someone pushed an md file which clearly is not a secret. 

So, from the point of view of kb8or it does what it has to do. So, the error is not a failure, still, not stoping the deploy because of an error is something that I, personally, find useful.

**Comment by lewismarshall** [comment]
Made me think about improving secrets Kb8or secrets schema though! :+1:

**Comment by lewismarshall** [comment]
OK, so created new issue #85 - will close this.
